# Medical Chat System Configuration

model:
  name: "facebook/bart-base"
  max_input_length: 512
  max_target_length: 256
  device: "auto"  # auto, cpu, cuda


training:
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  learning_rate: 5e-5
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  logging_steps: 100
  save_total_limit: 2
  load_best_model_at_end: true
  gradient_accumulation_steps: 1
  fp16: false
  dataloader_pin_memory: false


data:
  data_file: null  # Path to training data file
  test_size: 0.2
  val_size: 0.1
  augment_data: true
  min_question_length: 10
  min_answer_length: 20


rag:
  embedding_model: "all-MiniLM-L6-v2"
  generator_model: "facebook/bart-base"
  top_k: 3
  similarity_threshold: 0.5


api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true
  log_level: "info"


logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "medical_chat.log"


generation:
  max_length: 256
  num_beams: 4
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.2
  no_repeat_ngram_size: 2
  early_stopping: true


evaluation:
  metrics:
    - "rouge"
    - "bleu"
    - "medical_accuracy"
    - "response_quality"
  rouge_types:
    - "rouge1"
    - "rouge2"
    - "rougeL"
  save_predictions: true
  output_dir: "evaluation_results"
